In [1117]:
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
%matplotlib inline
import os
os.chdir("/Volumes/General Har/Data_Sets/rpcsv")

In [1118]:
ds = pd.read_csv('hospital_patients.csv')

In [1119]:
pd.Series(ds.columns)

0                 encounter_id
1                  patient_nbr
2                         race
3                       gender
4                          age
5                       weight
6            admission_type_id
7     discharge_disposition_id
8          admission_source_id
9             time_in_hospital
10                  payer_code
11           medical_specialty
12          num_lab_procedures
13              num_procedures
14             num_medications
15           number_outpatient
16            number_emergency
17            number_inpatient
18                      diag_1
19                      diag_2
20                      diag_3
21            number_diagnoses
22               max_glu_serum
23                   A1Cresult
24                   metformin
25                 repaglinide
26                 nateglinide
27              chlorpropamide
28                 glimepiride
29               acetohexamide
30                   glipizide
31                   glyburide
32      

In [1120]:
final_list=['age','time_in_hospital','num_medications','number_diagnoses','metformin',
           'chlorpropamide','glimepiride','tolazamide','insulin','race','admission_type_id',
           'admission_source_id','max_glu_serum','A1Cresult','readmitted']

In [1121]:
len(final_list)

15

In [1122]:
ds=ds[final_list]

In [1123]:
ds

age  time_in_hospital  num_medications  number_diagnoses  \
0        [0-10)                 1                1                 1   
1       [10-20)                 3               18                 9   
2       [20-30)                 2               13                 6   
3       [30-40)                 2               16                 7   
4       [40-50)                 1                8                 5   
...         ...               ...              ...               ...   
101761  [70-80)                 3               16                 9   
101762  [80-90)                 5               18                 9   
101763  [70-80)                 1                9                13   
101764  [80-90)                10               21                 9   
101765  [70-80)                 6                3                 9   

       metformin chlorpropamide glimepiride tolazamide insulin  \
0             No             No          No         No      No   
1             No             No          No         No      Up   
2             No             No          No         No      No   
3             No             No          No         No      Up   
4             No             No          No         No  Steady   
...          ...            ...         ...        ...     ...   
101761    Steady             No          No         No    Down   
101762        No             No          No         No  Steady   
101763    Steady             No          No         No    Down   
101764        No             No          No         No      Up   
101765        No             No          No         No      No   

                   race  admission_type_id  admission_source_id max_glu_serum  \
0             Caucasian                  6                    1          None   
1             Caucasian                  1                    7          None   
2       AfricanAmerican                  1                    7          None   
3             Caucasian                  1                    7          None   
4             Caucasian                  1                    7          None   
...                 ...                ...                  ...           ...   
101761  AfricanAmerican                  1                    7          None   
101762  AfricanAmerican                  1                    5          None   
101763        Caucasian                  1                    7          None   
101764        Caucasian                  2                    7          None   
101765        Caucasian                  1                    7          None   

       A1Cresult readmitted  
0           None         NO  
1           None        >30  
2           None         NO  
3           None         NO  
4           None         NO  
...          ...        ...  
101761        >8        >30  
101762      None         NO  
101763      None         NO  
101764      None         NO  
101765      None         NO  

[101766 rows x 15 columns]

In [1124]:
ds['age'] = ds['age'].replace('[70-80)', '70-80')
ds['age'] = ds['age'].replace('[60-70)', '60-70')
ds['age'] = ds['age'].replace('[50-60)', '50-60')
ds['age'] = ds['age'].replace('[0-10)', '0-10')

ds['age'] = ds['age'].replace('[80-90)', '80-90')
ds['age'] = ds['age'].replace('[40-50)', '40-50')
ds['age'] = ds['age'].replace('[30-40)', '30-40')

ds['age'] = ds['age'].replace('[90-100)', '90-100')
ds['age'] = ds['age'].replace('[20-30)', '20-30')
ds['age'] = ds['age'].replace('[10-20)', '10-20')

In [1125]:
ds.dtypes

age                    object
time_in_hospital        int64
num_medications         int64
number_diagnoses        int64
metformin              object
chlorpropamide         object
glimepiride            object
tolazamide             object
insulin                object
race                   object
admission_type_id       int64
admission_source_id     int64
max_glu_serum          object
A1Cresult              object
readmitted             object
dtype: object

In [1126]:
ds.isna().sum()

age                    0
time_in_hospital       0
num_medications        0
number_diagnoses       0
metformin              0
chlorpropamide         0
glimepiride            0
tolazamide             0
insulin                0
race                   0
admission_type_id      0
admission_source_id    0
max_glu_serum          0
A1Cresult              0
readmitted             0
dtype: int64

In [1127]:
cat_col=['age','metformin','chlorpropamide','glimepiride','tolazamide','insulin','race',
        'max_glu_serum','A1Cresult','admission_type_id'
         ,'admission_source_id']

In [1128]:
for ele in cat_col:
    print(ds[ele].value_counts())


70-80     26068
60-70     22483
50-60     17256
80-90     17197
40-50      9685
30-40      3775
90-100     2793
20-30      1657
10-20       691
0-10        161
Name: age, dtype: int64
No        81778
Steady    18346
Up         1067
Down        575
Name: metformin, dtype: int64
No        101680
Steady        79
Up             6
Down           1
Name: chlorpropamide, dtype: int64
No        96575
Steady     4670
Up          327
Down        194
Name: glimepiride, dtype: int64
No        101727
Steady        38
Up             1
Name: tolazamide, dtype: int64
No        47383
Steady    30849
Down      12218
Up        11316
Name: insulin, dtype: int64
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: race, dtype: int64
None    96420
Norm     2597
>200     1485
>300     1264
Name: max_glu_serum, dtype: int64
None    84748
>8       8216
Norm     4990
>7       3812
Name: A1Cresult, dtype: int6

In [1129]:
ds.dtypes

age                    object
time_in_hospital        int64
num_medications         int64
number_diagnoses        int64
metformin              object
chlorpropamide         object
glimepiride            object
tolazamide             object
insulin                object
race                   object
admission_type_id       int64
admission_source_id     int64
max_glu_serum          object
A1Cresult              object
readmitted             object
dtype: object

In [1130]:
num_cols=['time_in_hospital','num_medications','number_diagnoses']

In [1131]:
for ele in num_cols:
    print(ds[ele].value_counts())


3     17756
2     17224
1     14208
4     13924
5      9966
6      7539
7      5859
8      4391
9      3002
10     2342
11     1855
12     1448
13     1210
14     1042
Name: time_in_hospital, dtype: int64
13    6086
12    6004
11    5795
15    5792
14    5707
      ... 
70       2
75       2
74       1
79       1
81       1
Name: num_medications, Length: 75, dtype: int64
9     49474
5     11393
8     10616
7     10393
6     10161
4      5537
3      2835
2      1023
1       219
16       45
10       17
13       16
11       11
15       10
12        9
14        7
Name: number_diagnoses, dtype: int64


In [1132]:
#Now will Scale the numeric columns and will encode the categorical columns

In [1133]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import LabelEncoder

In [1134]:
ds['readmitted'] = ds['readmitted'].replace('>30', 0)
ds['readmitted'] = ds['readmitted'].replace('<30', 1)
ds['readmitted'] = ds['readmitted'].replace('NO', 2)

In [1135]:
X=ds.drop('readmitted',axis='columns')


In [1136]:
transformer = make_column_transformer(    #Transforming
    (MinMaxScaler(),num_cols),
    (OneHotEncoder(),cat_col)
)

In [1137]:
ydroplist=num_cols+cat_col
y=ds.drop(ydroplist,axis='columns')
y

readmitted
0                2
1                0
2                2
3                2
4                2
...            ...
101761           0
101762           2
101763           2
101764           2
101765           2

[101766 rows x 1 columns]

In [1138]:

transformer1=make_column_transformer(
    (OneHotEncoder(),['readmitted'])
)
transformer1.fit(y)
y=transformer1.transform(y)

In [1139]:
transformer.fit(X)

ColumnTransformer(transformers=[('minmaxscaler', MinMaxScaler(),
                                 ['time_in_hospital', 'num_medications',
                                  'number_diagnoses']),
                                ('onehotencoder', OneHotEncoder(),
                                 ['age', 'metformin', 'chlorpropamide',
                                  'glimepiride', 'tolazamide', 'insulin',
                                  'race', 'max_glu_serum', 'A1Cresult',
                                  'admission_type_id',
                                  'admission_source_id'])])

In [1140]:
X=transformer.transform(X)

In [1141]:
#X=transformer.transform(X)

In [1142]:
ds.readmitted

0         2
1         0
2         2
3         2
4         2
         ..
101761    0
101762    2
101763    2
101764    2
101765    2
Name: readmitted, Length: 101766, dtype: int64

In [1143]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [1144]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()

In [1145]:
model.add(Dense(input_dim=71,activation='relu',units=60, kernel_initializer='random_uniform')) #Input Layer


In [1146]:
for i in range(4):
    model.add(Dense(activation='relu',units=60, kernel_initializer='random_uniform')) #Hidden Layer

In [1147]:
model.add(Dense(activation='softmax',units=3,kernel_initializer='random_uniform')) #Output Layer

In [1148]:
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy']) #adam=batch g

In [1149]:
model.fit(x_train,y_train,epochs=400,batch_size=32)

Epoch 1/400
2545/2545 [==============================] - 13s 5ms/step - loss: 0.9399 - accuracy: 0.5388
Epoch 2/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.9308 - accuracy: 0.5393
Epoch 3/400
2545/2545 [==============================] - 6s 2ms/step - loss: 0.9291 - accuracy: 0.5397
Epoch 4/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.9274 - accuracy: 0.5426
Epoch 5/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.9258 - accuracy: 0.5446
Epoch 6/400
2545/2545 [==============================] - 6s 2ms/step - loss: 0.9244 - accuracy: 0.5456
Epoch 7/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.9232 - accuracy: 0.5471
Epoch 8/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.9225 - accuracy: 0.5477
Epoch 9/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.9214 - accuracy: 0.5479
Epoch 10/400
2545/2545 [==============================] - 8s 3ms/step - 

2545/2545 [==============================] - 6s 2ms/step - loss: 0.8744 - accuracy: 0.5753
Epoch 80/400
2545/2545 [==============================] - 5s 2ms/step - loss: 0.8734 - accuracy: 0.5744
Epoch 81/400
2545/2545 [==============================] - 9s 3ms/step - loss: 0.8734 - accuracy: 0.5757
Epoch 82/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.8727 - accuracy: 0.5740
Epoch 83/400
2545/2545 [==============================] - 12s 5ms/step - loss: 0.8729 - accuracy: 0.5747
Epoch 84/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8716 - accuracy: 0.5761
Epoch 85/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8713 - accuracy: 0.5761
Epoch 86/400
2545/2545 [==============================] - 9s 4ms/step - loss: 0.8709 - accuracy: 0.5754
Epoch 87/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.8704 - accuracy: 0.5755
Epoch 88/400
2545/2545 [==============================] - 8s 3ms/step - lo

2545/2545 [==============================] - 11s 4ms/step - loss: 0.8453 - accuracy: 0.5880
Epoch 157/400
2545/2545 [==============================] - 12s 5ms/step - loss: 0.8475 - accuracy: 0.5863
Epoch 158/400
2545/2545 [==============================] - 12s 5ms/step - loss: 0.8457 - accuracy: 0.5876
Epoch 159/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8450 - accuracy: 0.5877
Epoch 160/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.8451 - accuracy: 0.5872
Epoch 161/400
2545/2545 [==============================] - 11s 4ms/step - loss: 0.8446 - accuracy: 0.5870
Epoch 162/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8445 - accuracy: 0.5872
Epoch 163/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8452 - accuracy: 0.5873
Epoch 164/400
2545/2545 [==============================] - 11s 4ms/step - loss: 0.8442 - accuracy: 0.5888
Epoch 165/400
2545/2545 [==============================] - 11

2545/2545 [==============================] - 12s 5ms/step - loss: 0.8291 - accuracy: 0.5947
Epoch 233/400
2545/2545 [==============================] - 9s 3ms/step - loss: 0.8299 - accuracy: 0.5941
Epoch 234/400
2545/2545 [==============================] - 9s 4ms/step - loss: 0.8291 - accuracy: 0.5943
Epoch 235/400
2545/2545 [==============================] - 8s 3ms/step - loss: 0.8283 - accuracy: 0.5947
Epoch 236/400
2545/2545 [==============================] - 9s 3ms/step - loss: 0.8291 - accuracy: 0.5947
Epoch 237/400
2545/2545 [==============================] - 9s 3ms/step - loss: 0.8302 - accuracy: 0.5953
Epoch 238/400
2545/2545 [==============================] - 10s 4ms/step - loss: 0.8284 - accuracy: 0.5950
Epoch 239/400
2545/2545 [==============================] - 9s 4ms/step - loss: 0.8291 - accuracy: 0.5946
Epoch 240/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8284 - accuracy: 0.5938
Epoch 241/400
2545/2545 [==============================] - 6s 3ms/s

2545/2545 [==============================] - 7s 3ms/step - loss: 0.8169 - accuracy: 0.6001
Epoch 310/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8181 - accuracy: 0.5991
Epoch 311/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8186 - accuracy: 0.5990
Epoch 312/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8175 - accuracy: 0.5997
Epoch 313/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8160 - accuracy: 0.5996
Epoch 314/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8185 - accuracy: 0.5992
Epoch 315/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8187 - accuracy: 0.5982
Epoch 316/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8169 - accuracy: 0.6001
Epoch 317/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8180 - accuracy: 0.5999
Epoch 318/400
2545/2545 [==============================] - 7s 3ms/ste

Epoch 387/400
2545/2545 [==============================] - 6s 2ms/step - loss: 0.8089 - accuracy: 0.6039
Epoch 388/400
2545/2545 [==============================] - 6s 2ms/step - loss: 0.8089 - accuracy: 0.6036
Epoch 389/400
2545/2545 [==============================] - 7s 3ms/step - loss: 0.8090 - accuracy: 0.6035
Epoch 390/400
2545/2545 [==============================] - 5s 2ms/step - loss: 0.8090 - accuracy: 0.6036
Epoch 391/400
2545/2545 [==============================] - 6s 2ms/step - loss: 0.8093 - accuracy: 0.6036
Epoch 392/400
2545/2545 [==============================] - 6s 3ms/step - loss: 0.8088 - accuracy: 0.6032
Epoch 393/400
2545/2545 [==============================] - 5s 2ms/step - loss: 0.8079 - accuracy: 0.6039
Epoch 394/400
2545/2545 [==============================] - 5s 2ms/step - loss: 0.8107 - accuracy: 0.6041
Epoch 395/400
2545/2545 [==============================] - 5s 2ms/step - loss: 0.8070 - accuracy: 0.6044
Epoch 396/400
2545/2545 [==============================

# ANN Evaluation

In [1197]:
y_predict = model.predict(x_test)

In [1199]:
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score,confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_test.argmax(axis=1),y_predict.argmax(axis=1))*100))
print("Recall score : %f" %(recall_score(y_test.argmax(axis=1),y_predict.argmax(axis=1), average= 'weighted')*100))
print("ROC score : %f" %(roc_auc_score(y_test,y_predict)*100))
print(confusion_matrix(y_test.argmax(axis=1),y_predict.argmax(axis=1)))


Accuracy score: 52.618650
Recall score : 52.618650
ROC score : 56.615408
[[1734   83 5299]
 [ 537   26 1678]
 [1870  177 8950]]


In [1150]:
x_train.shape

(81412, 71)

In [1152]:
# Why was this line wrong? from tensorflow import keras.models.load_model
from tensorflow import keras
model = keras.models.load_model("price_prediction_model.h5")
transformer = joblib.load("data_transformer.joblib")

In [1153]:
ds.columns

Index(['age', 'time_in_hospital', 'num_medications', 'number_diagnoses',
       'metformin', 'chlorpropamide', 'glimepiride', 'tolazamide', 'insulin',
       'race', 'admission_type_id', 'admission_source_id', 'max_glu_serum',
       'A1Cresult', 'readmitted'],
      dtype='object')

In [1154]:
newdict={
    'age': ['70-80'],
    'time_in_hospital': [3],
     'num_medications': [16],
     'number_diagnoses': [9],
     'metformin':['Steady'],
     'chlorpropamide':['No'],
     'glimepiride':['No'],
     'tolazamide':['No'],
     'insulin':['Down'],
      'race':['AfricanAmerican'],
     'admission_type_id':[1],
     'admission_source_id':[7],
     'max_glu_serum':['None'],
    'A1Cresult':['None']
}
    
    
newds=pd.DataFrame(newdict)
newds
    
    
    
    
    


age  time_in_hospital  num_medications  number_diagnoses metformin  \
0  70-80                 3               16                 9    Steady   

  chlorpropamide glimepiride tolazamide insulin             race  \
0             No          No         No    Down  AfricanAmerican   

   admission_type_id  admission_source_id max_glu_serum A1Cresult  
0                  1                    7          None      None

In [1155]:
prediction = model.predict(transformer.transform(newds))

In [1157]:
maxElement = np.amax(prediction)
maxElement


max_index_col = np.argmax(prediction, axis=1) # This is how you do it
print(max_index_col)

[0]


In [1159]:
for n in enumerate(newds.dtypes):
    print(n)

(0, dtype('O'))
(1, dtype('int64'))
(2, dtype('int64'))
(3, dtype('int64'))
(4, dtype('O'))
(5, dtype('O'))
(6, dtype('O'))
(7, dtype('O'))
(8, dtype('O'))
(9, dtype('O'))
(10, dtype('int64'))
(11, dtype('int64'))
(12, dtype('O'))
(13, dtype('O'))


# Random Forest

In [1162]:
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth = 10,criterion='gini',min_samples_split = 15, random_state = 0)
rmf_clf = rmf.fit(x_train,y_train)

In [1201]:
y_predict = rmf_clf.predict(x_test)

In [1203]:
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score,confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_test.argmax(axis=1),y_predict.argmax(axis=1))*100))
print("Recall score : %f" %(recall_score(y_test,y_predict, average='samples')))
print("ROC score : %f" %(roc_auc_score(y_test,y_predict)))
print(confusion_matrix(y_test.argmax(axis=1),y_predict.argmax(axis=1)))


Accuracy score: 53.331041
Recall score : 0.384249
ROC score : 0.522932
[[3039    0 4077]
 [ 952    0 1289]
 [3181    0 7816]]


In [1200]:
ds.corr()

time_in_hospital  num_medications  number_diagnoses  \
time_in_hospital             1.000000         0.466135          0.220186   
num_medications              0.466135         1.000000          0.261526   
number_diagnoses             0.220186         0.261526          1.000000   
admission_type_id           -0.012500         0.079535         -0.117126   
admission_source_id         -0.006965        -0.054533          0.072114   
readmitted                  -0.040309        -0.037399         -0.104660   

                     admission_type_id  admission_source_id  readmitted  
time_in_hospital             -0.012500            -0.006965   -0.040309  
num_medications               0.079535            -0.054533   -0.037399  
number_diagnoses             -0.117126             0.072114   -0.104660  
admission_type_id             1.000000             0.106654    0.001342  
admission_source_id           0.106654             1.000000   -0.041193  
readmitted                    0.001342            -0.041193    1.000000